import cv2
import numpy as np
def empty(a):
  pass
cv2.namedWindow("TrackBars")
cv2.resizeWindow("TrackBars",640,240)
cv2.createTrackbar("H min","TrackBars",0,179,empty)
cv2.createTrackbar("H max","TrackBars",179,179,empty)
cv2.createTrackbar("S min","TrackBars",0,255,empty)
cv2.createTrackbar("S max","TrackBars",255,255,empty)
cv2.createTrackbar("V min","TrackBars",0,255,empty)
cv2.createTrackbar("V max","TrackBars",255,255,empty)
while True:
  h_min=cv2.getTrackbarPos("H min","TrackBars")
  h_max=cv2.getTrackbarPos("H max","TrackBars")
  s_min=cv2.getTrackbarPos("S min","TrackBars")
  s_max=cv2.getTrackbarPos("S max","TrackBars")
  v_min=cv2.getTrackbarPos("V min","TrackBars")
  v_max=cv2.getTrackbarPos("V max","TrackBars")
  img=cv2.imread('cat.jpg')
  hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
  lower=np.array([h_min,s_min,v_min])
  upper=np.array([h_max,s_max,v_max])
  mask=cv2.inRange(hsv,lower,upper)
  res=cv2.bitwise_and(img,img,mask=mask)
  cv2.imshow('img',img)
  cv2.imshow('mask',mask)
  cv2.imshow('res',res)
  cv2.waitKey(1)
cv2.destroyAllWindows()
